[package]
name = "courier"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slint = "0.2.0"
clap = "3.0.14"
log = "0.4.16"
pretty_env_logger = "0.4.0"
